# Generated by Django 3.2.16 on 2024-08-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField(auto_created=True)),
                ('name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=50)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=20)),
                ('localitation', models.TextField(max_length=255)),
                ('reputation', models.CharField(choices=[('None', 'None'), ('Bad', 'Bad'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='None', max_length=30)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
