# Generated by Django 3.2.16 on 2024-08-21 07:45

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imageUrl', models.TextField(default=apps.product.models.product_image_directory, editable=False)),
                ('category', models.CharField(choices=[('None', 'None'), ('Computers & Tablets', 'Computers & Tablets'), ('Mobile Phones', 'Mobile Phones'), ('Accessories', 'Accessories'), ('Home Appliances', 'Home Appliances'), ("Men's Clothing", "Men's Clothing"), ("Women's Clothing", "Women's Clothing"), ("Children's Clothing", "Children's Clothing"), ('Footwear', 'Footwear'), ('Furniture', 'Furniture'), ('Kitchenware', 'Kitchenware'), ('Bedding', 'Bedding'), ('Home Decor', 'Home Decor'), ('Skincare', 'Skincare'), ('Haircare', 'Haircare'), ('Personal Care', 'Personal Care'), ('Supplements', 'Supplements'), ('Fitness Equipment', 'Fitness Equipment'), ('Outdoor Gear', 'Outdoor Gear'), ('Sportswear', 'Sportswear'), ('Camping Equipment', 'Camping Equipment'), ('Car Accessories', 'Car Accessories'), ('Motorcycle Parts', 'Motorcycle Parts'), ('Tools & Equipment', 'Tools & Equipment'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Educational', 'Educational'), ('Office Supplies', 'Office Supplies'), ('Action Figures', 'Action Figures'), ('Board Games', 'Board Games'), ('Educational Toys', 'Educational Toys'), ('Video Games', 'Video Games'), ('Fresh Produce', 'Fresh Produce'), ('Packaged Foods', 'Packaged Foods'), ('Beverages', 'Beverages'), ('Household Supplies', 'Household Supplies'), ('Pet Food', 'Pet Food'), ('Pet Toys', 'Pet Toys'), ('Grooming Products', 'Grooming Products'), ('Pet Accessories', 'Pet Accessories')], default='None', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(max_length=50, upload_to=apps.product.models.product_image_directory)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('time_stamp', models.IntegerField(default=0)),
            ],
        ),
    ]
