# Generated by Django 3.2.16 on 2024-08-21 08:05

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=255, upload_to=apps.product.models.product_image_directory),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(default=apps.product.models.product_image_directory, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
