# Generated by Django 3.2.16 on 2024-08-21 08:51

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=500, upload_to=apps.product.models.product_image_directory),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
